"""New Migration

Revision ID: 20139836216c
Revises: 
Create Date: 2022-08-18 23:01:35.684541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20139836216c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FBPAGE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FBPAGE_id'), 'FBPAGE', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_FBPAGE_id'), table_name='FBPAGE')
    op.drop_table('FBPAGE')
    # ### end Alembic commands ###
