"""1  Migration

Revision ID: 46378a2bac9c
Revises: 913820a50c16
Create Date: 2022-08-19 01:48:17.481233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46378a2bac9c'
down_revision = '913820a50c16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
