"""1  Migration

Revision ID: 66e96d29c8d8
Revises: efb7db437467
Create Date: 2022-08-19 02:01:32.994769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e96d29c8d8'
down_revision = 'efb7db437467'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
