"""second Migration

Revision ID: 913820a50c16
Revises: 20139836216c
Create Date: 2022-08-19 01:03:30.594661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913820a50c16'
down_revision = '20139836216c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FBPAGE', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('FBPAGE', sa.Column('post_url', sa.String(length=255), nullable=True))
    op.add_column('FBPAGE', sa.Column('text', sa.String(length=255), nullable=True))
    op.add_column('FBPAGE', sa.Column('time', sa.String(length=255), nullable=True))
    op.add_column('FBPAGE', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('FBPAGE', sa.Column('likes', sa.Integer(), nullable=True))
    op.add_column('FBPAGE', sa.Column('comments', sa.Integer(), nullable=True))
    op.add_column('FBPAGE', sa.Column('shares', sa.Integer(), nullable=True))
    op.drop_column('FBPAGE', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FBPAGE', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('FBPAGE', 'shares')
    op.drop_column('FBPAGE', 'comments')
    op.drop_column('FBPAGE', 'likes')
    op.drop_column('FBPAGE', 'image')
    op.drop_column('FBPAGE', 'time')
    op.drop_column('FBPAGE', 'text')
    op.drop_column('FBPAGE', 'post_url')
    op.drop_column('FBPAGE', 'post_id')
    # ### end Alembic commands ###
