"""1  Migration

Revision ID: 9a69fc288c6f
Revises: f9c85de9fca0
Create Date: 2022-08-19 01:56:30.277189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a69fc288c6f'
down_revision = 'f9c85de9fca0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
