"""2  Migration

Revision ID: f9c85de9fca0
Revises: 46378a2bac9c
Create Date: 2022-08-19 01:55:12.587644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c85de9fca0'
down_revision = '46378a2bac9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
